### ISSUE TITLE
1.28.01 - unable to edit character

### ISSUE THREAD

**Issue by riyth** [NerdyMusician/GAMMA#6]
After updating from v1.27.04, I received the error below when selecting the "Edit Character" button on the info tab, attempting to level up my character. 

![GAMMA_Error](https://user-images.githubusercontent.com/7293693/149844786-bc0d354c-cea7-45c4-b38d-07072384d1f1.png)

**Comment by NerdyMusician** [comment]
Thank you for the feedback! This issue will be addressed in the following release (1.28.01) but from my testing the character data itself should be intact and still able to be used in gameplay, but just not edited in the wizard.

Technical Info on the Bug: 
The reason for the issue has to do with the change I made for the DeepClone method, utilizing the XmlSerializer instead of the BinaryFormatter. 
During character editing, it actually creates a clone of the character to modify as a way of protecting the original data, and there ended up being an issue with a circular dependency between the CharacterModel object and the InventoryModel.Owner property.
Going forward, the InventoryModel.Owner property no longer exists, and other methods have been put in place to call for the character inventory stats to be updated when the Inventory's item list changes.
